### Create Post
POST http://localhost:8082/api/v1/posts
Content-Type: application/json
X-User-Id: 71da0869-6266-4377-93f0-f64eb613fc51

{
  "title": "helll",
  "content": "Logged in",
  "visibility": "PUBLIC",
  "hashtags": [
    "#Logged in"
  ],
  "mediaUrls": [
    "http://localhost:8082/api/v1/swagger-ui/index.html#/post-controller/createPost"
  ]
}
